server:
  port: 9000

spring:
  application:
    name: ordermanagement
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MM_IMS_DB_URL}
    username: ${MM_IMS_DB_USER}
    password: ${MM_IMS_DB_PASS}
hibernate:
  transaction:
    jta:
      platform: enabled
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
