
services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: cogent
#      MYSQL_DATABASE: testdb
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysq_data:/var/lib/mysql

  app:
    build: .
#    depends_on:
#      - mysql
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/capstone
      SPRING_DATASOURCE_USERNAME : cogent
      SPRING_DATASOURCE_PASSWORD : cogent
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://client-app-1:8761/eureka
    networks:
      capstone:
        aliases:
          - app

volumes:
  mysq_data:  # Define the mysq_data volume
    driver: local


networks:
  capstone:
    name: capstone1
    external: true
    driver: bridge